-- 009_create_analysis_module_artifacts.sql

CREATE TABLE IF NOT EXISTS analysis_module_artifacts (
    id INT NOT NULL AUTO_INCREMENT,
    artifact_id VARCHAR(64) NOT NULL,
    user_id INT NOT NULL,
    workspace_id VARCHAR(128) NOT NULL,
    role VARCHAR(64) NOT NULL,
    conversation_id VARCHAR(128) NOT NULL,
    analysis_session_id VARCHAR(64) NULL,
    analysis_session_revision INT NOT NULL DEFAULT 0,
    module_id VARCHAR(64) NOT NULL,
    module_run_id VARCHAR(64) NULL,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'completed',
    content_type VARCHAR(64) NOT NULL DEFAULT 'text/markdown',
    markdown_body LONGTEXT NULL,
    text_body LONGTEXT NULL,
    artifact_json JSON NULL,
    metadata_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_analysis_module_artifacts_artifact_id (artifact_id),
    INDEX ix_analysis_module_artifacts_artifact_id (artifact_id),
    INDEX ix_analysis_module_artifacts_user_id (user_id),
    INDEX ix_analysis_module_artifacts_workspace_id (workspace_id),
    INDEX ix_analysis_module_artifacts_role (role),
    INDEX ix_analysis_module_artifacts_conversation_id (conversation_id),
    INDEX ix_analysis_module_artifacts_session (analysis_session_id, analysis_session_revision),
    INDEX ix_analysis_module_artifacts_module_run (module_id, module_run_id),
    INDEX ix_analysis_module_artifacts_scope_created (user_id, workspace_id, role, conversation_id, created_at),
    CONSTRAINT fk_analysis_module_artifacts_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);
