from .agent import (
    generate_paginated_report,
    generate_report_artifact_from_source_documents,
)
from .contracts import PAGINATED_REPORT_BUNDLE_SCHEMA_VERSION
from .module_artifacts import (
    analysis_module_artifact_to_payload,
    build_analysis_module_artifacts,
    get_analysis_module_artifacts_by_ids,
    save_analysis_module_artifacts,
)
from .renderers import render_bundle_html, render_bundle_markdown, render_bundle_pdf
from .service import (
    DEFAULT_REPORT_RENDER_STYLE,
    REPORT_REQUEST_GENERATE,
    REPORT_REQUEST_REGENERATE,
    ReportRequestError,
    ReportActionError,
    REPORT_DOWNLOAD_FORMAT,
    PublishedReportValidationError,
    SUPPORTED_REPORT_DOWNLOAD_FORMATS,
    analysis_report_to_payload,
    attach_analysis_session_scope,
    delete_legacy_report_rows,
    execute_report_request,
    find_report_asset,
    get_analysis_report,
    has_report_request,
    inline_asset_response_payload,
    normalize_report_request,
    persist_report_artifact_result,
    render_report_pdf,
    report_preview_metadata,
    report_row_forbidden_values,
    safe_report_filename,
    save_analysis_report_artifact,
)

__all__ = [
    "PAGINATED_REPORT_BUNDLE_SCHEMA_VERSION",
    "DEFAULT_REPORT_RENDER_STYLE",
    "REPORT_REQUEST_GENERATE",
    "REPORT_REQUEST_REGENERATE",
    "ReportRequestError",
    "ReportActionError",
    "REPORT_DOWNLOAD_FORMAT",
    "PublishedReportValidationError",
    "SUPPORTED_REPORT_DOWNLOAD_FORMATS",
    "analysis_module_artifact_to_payload",
    "analysis_report_to_payload",
    "build_analysis_module_artifacts",
    "attach_analysis_session_scope",
    "delete_legacy_report_rows",
    "execute_report_request",
    "find_report_asset",
    "generate_paginated_report",
    "generate_report_artifact_from_source_documents",
    "get_analysis_module_artifacts_by_ids",
    "get_analysis_report",
    "has_report_request",
    "inline_asset_response_payload",
    "normalize_report_request",
    "persist_report_artifact_result",
    "render_bundle_html",
    "render_bundle_markdown",
    "render_bundle_pdf",
    "render_report_pdf",
    "report_preview_metadata",
    "report_row_forbidden_values",
    "safe_report_filename",
    "save_analysis_module_artifacts",
    "save_analysis_report_artifact",
]
