from __future__ import annotations

from typing import Any

from .repository import RoboticsEvidenceRepository


INITIAL_ROBOTICS_LISTED_COMPANY_PROFILES: tuple[dict[str, Any], ...] = (
    {
        "stock_code": "688169",
        "exchange": "SSE",
        "market": "科创板",
        "security_name": "石头科技",
        "company_name": "北京石头世纪科技股份有限公司",
        "aliases": ["石头", "Roborock", "石头科技股份有限公司"],
        "industry_segments": ["扫地机器人", "服务机器人"],
        "robotics_keywords": ["扫地机器人", "清洁机器人", "服务机器人", "机器人"],
        "cninfo_column": "sse",
        "is_supported": True,
    },
    {
        "stock_code": "603486",
        "exchange": "SSE",
        "market": "主板",
        "security_name": "科沃斯",
        "company_name": "科沃斯机器人股份有限公司",
        "aliases": ["科沃斯机器人", "Ecovacs"],
        "industry_segments": ["扫地机器人", "服务机器人"],
        "robotics_keywords": ["扫地机器人", "清洁机器人", "服务机器人", "机器人"],
        "cninfo_column": "sse",
        "is_supported": True,
    },
    {
        "stock_code": "002747",
        "exchange": "SZSE",
        "market": "深市主板",
        "security_name": "埃斯顿",
        "company_name": "南京埃斯顿自动化股份有限公司",
        "aliases": ["埃斯顿自动化", "ESTUN"],
        "industry_segments": ["工业机器人", "控制器", "智能制造"],
        "robotics_keywords": ["工业机器人", "控制器", "伺服系统", "智能制造"],
        "cninfo_column": "szse",
        "is_supported": True,
    },
    {
        "stock_code": "688017",
        "exchange": "SSE",
        "market": "科创板",
        "security_name": "绿的谐波",
        "company_name": "苏州绿的谐波传动科技股份有限公司",
        "aliases": ["绿的", "绿的谐波传动"],
        "industry_segments": ["核心零部件", "减速器"],
        "robotics_keywords": ["谐波减速器", "减速器", "核心零部件", "机器人"],
        "cninfo_column": "sse",
        "is_supported": True,
    },
    {
        "stock_code": "300124",
        "exchange": "SZSE",
        "market": "创业板",
        "security_name": "汇川技术",
        "company_name": "深圳市汇川技术股份有限公司",
        "aliases": ["汇川", "Inovance"],
        "industry_segments": ["控制器", "伺服系统", "智能制造"],
        "robotics_keywords": ["控制器", "伺服系统", "工业自动化", "智能制造", "机器人"],
        "cninfo_column": "szse",
        "is_supported": True,
    },
    {
        "stock_code": "002050",
        "exchange": "SZSE",
        "market": "深市主板",
        "security_name": "三花智控",
        "company_name": "浙江三花智能控制股份有限公司",
        "aliases": ["三花", "三花智能控制"],
        "industry_segments": ["执行器", "热管理", "人形机器人上游"],
        "robotics_keywords": ["执行器", "机器人零部件", "人形机器人", "热管理"],
        "cninfo_column": "szse",
        "is_supported": True,
    },
    {
        "stock_code": "601689",
        "exchange": "SSE",
        "market": "主板",
        "security_name": "拓普集团",
        "company_name": "宁波拓普集团股份有限公司",
        "aliases": ["拓普", "拓普集团股份有限公司"],
        "industry_segments": ["执行器", "机器人上游"],
        "robotics_keywords": ["执行器", "机器人零部件", "人形机器人"],
        "cninfo_column": "sse",
        "is_supported": True,
    },
    {
        "stock_code": "603728",
        "exchange": "SSE",
        "market": "主板",
        "security_name": "鸣志电器",
        "company_name": "上海鸣志电器股份有限公司",
        "aliases": ["鸣志", "MOONS"],
        "industry_segments": ["电机", "机器人上游"],
        "robotics_keywords": ["电机", "步进电机", "伺服", "机器人零部件"],
        "cninfo_column": "sse",
        "is_supported": True,
    },
    {
        "stock_code": "002472",
        "exchange": "SZSE",
        "market": "深市主板",
        "security_name": "双环传动",
        "company_name": "浙江双环传动机械股份有限公司",
        "aliases": ["双环", "双环传动机械"],
        "industry_segments": ["减速器", "机器人上游"],
        "robotics_keywords": ["减速器", "齿轮", "机器人零部件"],
        "cninfo_column": "szse",
        "is_supported": True,
    },
    {
        "stock_code": "688322",
        "exchange": "SSE",
        "market": "科创板",
        "security_name": "奥比中光",
        "company_name": "奥比中光科技集团股份有限公司",
        "aliases": ["奥比中光科技", "Orbbec"],
        "industry_segments": ["传感器", "机器视觉"],
        "robotics_keywords": ["传感器", "3D视觉", "机器视觉", "机器人"],
        "cninfo_column": "sse",
        "is_supported": True,
    },
    {
        "stock_code": "09880",
        "exchange": "HKEX",
        "market": "港股",
        "security_name": "优必选",
        "company_name": "深圳市优必选科技股份有限公司",
        "aliases": ["优必选科技", "UBTECH"],
        "industry_segments": ["人形机器人", "服务机器人"],
        "robotics_keywords": ["人形机器人", "服务机器人", "机器人"],
        "is_supported": False,
        "unsupported_reason": "港股上市公司不属于本阶段 CNINFO A 股公告查询范围。",
    },
)


def seed_robotics_listed_company_profiles(repository: RoboticsEvidenceRepository) -> int:
    count = 0
    for payload in INITIAL_ROBOTICS_LISTED_COMPANY_PROFILES:
        repository.upsert_listed_company_profile({**payload, "source": "seed:robotics-v1"})
        count += 1
    return count
